### ISSUE TITLE
Fix compile issues and update project dependencies

### ISSUE THREAD

**Issue by claucookie** [CoVital-Project/HealthWatcher#1]
The scope of this issue is to make the project compile and generate an apk.

The project is 3 years old, which means it is not using the latest available versions to compile.

We need to update the build.gradle file to make sure the latest gradle plugin is used a long with the latest build tools and target api.

**Comment by Ian2020** [comment]
In a repo mentioned on slack by Yoni someone else appears to have attempted some upgrade work, see last 3 commits:

https://github.com/latinosamuel/HealthWatcher/commits/master

Hope this helps.
