### ISSUE TITLE
Save finger's pictures recorded by the camera

### ISSUE THREAD

**Issue by claucookie** [CoVital-Project/HealthWatcher#3]
When using the following features of the app:
- Heart rate
- Oxygen saturation.

We want to:
- Create a folder called `healthwatcher` inside a directory available for the user to access.
- Save the images taken by the camera into the folder for manual collection later.

Outstanding questions:
- How many pictures? TBC
- Name of the pictures? TBC

**Comment by MalcolmMielle** [comment]
I think either the picture or the video file would work.
* 30 fps is a framerate that has been used by other algorithms and it would be nice for testing so I would push for that specification.
* If we save pictures, it might be good to have their name be the image timestamps
